# Generated by Django 5.2.6 on 2025-11-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ride',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
