# Generated by Django 5.2.6 on 2025-11-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_app', '0002_ride_price_ride_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='seats_available',
            field=models.IntegerField(default=1),
        ),
    ]
