# Generated by Django 5.2.6 on 2025-11-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_app', '0002_booking'),
        ('ride_app', '0003_alter_ride_seats_available'),
    ]

    operations = [
    ]
