# Generated by Django 5.2.6 on 2025-11-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_app', '0004_merge_0002_booking_0003_alter_ride_seats_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
